### ISSUE TITLE
Creator role predicates

### ISSUE THREAD

**Issue by chrissyrissmeyer** [samvera-labs/houndstooth#1]
Rather than listing all [MARC relator predicates](http://id.loc.gov/vocabulary/relators.html) in metadata model, could we point to another configuration file that lists only the relators currently in use? How could we do that?

**Comment by remerjohnson** [comment]
I am looking into this... not quite sure of an ETA yet for a solution / pull request. 

So far, what seems like a possible solution is not to have two separate files where one calls the other (this seems to be not cool/desirable for the YAML spec), but a way where the code stitches together two files (meaning the roles file would be absorbed into the larger/master file).  

Hopefully that would be acceptable; I know the main desire here is not wanting to have a file where 80% of it is lengthy roles...

**Comment by remerjohnson** [comment]
Since we are now debating YAML vs. JSON as the data format, I think I will wait a bit until that is hashed out before offering a pull request. Would it be helpful to show/talk through how each data format could offer a solution to this issue?

**Comment by chrissyrissmeyer** [comment]
Based on group discussion, it seems as though we will want to enumerate all of the relators in the specification.
